name: docs.nextstrain.org
channels:
  - defaults
dependencies:
  - graphviz
  - make
  - pip
  - pip:
    - nextstrain-sphinx-theme>=2022.5
    - docutils<0.18
    - recommonmark
    - requests
    - sphinx
    - sphinx-autobuild
    - sphinx-markdown-tables
    - sphinx-argparse<0.5.0
    - sphinx-tabs
    - sphinx-copybutton
