name: docs.nextstrain.org
channels:
  - defaults
dependencies:
  - graphviz
  - make
  - pip
  - pip:
    - nextstrain-sphinx-theme>=2022.5
    - docutils
    - recommonmark
    - requests
    - sphinx>=7.1
    - sphinx-autobuild
    - sphinx-markdown-tables
    - sphinx-argparse
    - sphinx-tabs
    - sphinx-copybutton
