name: docs.nextstrain.org
channels:
  - defaults
dependencies:
  - graphviz
  - make
  - recommonmark
  - requests
  - sphinx
  - pip
  - pip:
    - nextstrain-sphinx-theme>=2020.2
    - sphinx-rtd-theme>=1.0.0rc1
    - sphinx-markdown-tables
    - sphinx-argparse
    - sphinx-tabs
