name: docs.nextstrain.org
channels:
  - defaults
dependencies:
  - graphviz
  - make
  - recommonmark
  - requests
  - sphinx>3,<4
  - pip
  - pip:
    - nextstrain-sphinx-theme>=2020.2
    - sphinx-markdown-tables
    - sphinx-argparse
    - sphinx-tabs
