name: docs.nextstrain.org
channels:
  - conda-forge
dependencies:
  - graphviz
  - make
  - recommonmark
  - requests
  - sphinx
  - sphinx-tabs
  - pip
  - docutils<0.17 # https://github.com/nextstrain/ncov/issues/891
  - pip:
    - nextstrain-sphinx-theme>=2020.2
    - sphinx-markdown-tables
    - sphinx-argparse
