name: docs.nextstrain.org
channels:
  - defaults
dependencies:
  - graphviz
  - make
  - pip
  - pip:
    - nextstrain-sphinx-theme>=2020.2
    - recommonmark
    - requests
    - sphinx
    - sphinx-markdown-tables
    - sphinx-argparse
    - sphinx-tabs
    - sphinx-copybutton
