name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  docs:
    name: docs
    uses: nextstrain/.github/.github/workflows/docs-ci.yaml@master
    with:
      environment-file: conda.yml
      docs-directory: .
      make-target: html
