name: Sync RTD redirects

on:
  push:
    branches:
      - master
    paths:
      - redirects.yml
      - .github/workflows/sync-redirects.yaml

  pull_request:

  # Manually triggered using GitHub's UI
  workflow_dispatch:

jobs:
  sync:
    name: rtd redirects
    uses: nextstrain/.github/.github/workflows/sync-rtd-redirects.yaml@master
    with:
      project: nextstrain
      file: redirects.yml
    secrets:
      RTD_TOKEN: ${{ secrets.RTD_TOKEN }}
